name: Create Pull Request on Ponrove

on:
  release:
    types: [published]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@dff4b11d10ecc84d937fdd0653d8343a88c5b9c4
        id: app-token
        with:
          app-id: ${{ secrets.PR_CREATION_PONROVE_APP_ID }}
          private-key: ${{ secrets.PR_CREATION_PONROVE_SECRET_KEY }}
          owner: ${{ github.repository_owner }}
          permission-contents: write
          permission-pull-requests: write
          repositories: ponrove

      - name: Checkout code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          repository: ${{ github.repository_owner }}/ponrove
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version-file: go.mod
      - name: Update
        id: update
        run: go get -u github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}@${{ github.event.release.tag_name }}
      - name: Tidy packages
        id: tidy-packages
        run: go mod tidy

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@0f2a09222f84e1d0d078fdec150cbe3ff4c5b799
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: "Release ${{ github.repository }} ${{ github.event.release.tag_name }}"
          body: "Release of version ${{ github.event.release.tag_name }} on ${{ github.repository }}"
          branch: "upgrade/frontend/release-${{ github.event.release.tag_name }}"
          commit-message: "Upgrade to version ${{ github.event.release.tag_name }} of ${{ github.repository }}"
          base: "main"
          draft: false
          sign-commits: true
